name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "welcom to our first GitHub Action"

      - name: Rheckout repository
        uses: actions/checkout@v4.3.1

      - name: List repo files
        run: ls -la
        

